image:
  file: .gitpod.Dockerfile
ports:
  - port: 3000
    onOpen: open-browser
tasks:
  - init: |
      yarn
      yarn compile
      yarn download-builtin-extensions
    command: |
      gp sync-done init
      export NODE_ENV=development
      export VSCODE_DEV=1
      yarn gulp watch-init
    name: watch app
  - command: |
      gp sync-await init
      export NODE_ENV=development
      export VSCODE_DEV=1
      yarn gulp watch-extension:gitpod
    name: watch extension
  - command: |
      gp sync-await init
      export NODE_ENV=development
      export VSCODE_DEV=1
      node out/gitpod.js
    name: run app
    openMode: split-right
github:
  prebuilds:
    pullRequestsFromForks: true
vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.3:1NRvj3UKNTNwmYjptmUmIw==
